### ISSUE TITLE
About the results after training

### ISSUE THREAD

**Issue by q-rong** [hobincar/RecNet#11]
Hi，
Thank you very much for your previous help. I have successfully obtained the training results.
I have two questions to ask you.
1. When I finished training the model, I can only obtain the scores of four metrics. How do I see the sentences generated by the model?
2. As your training results, why does your SA-LSTM model get a higher CIDEr score than RecNet (global  / local)? Is it the error?

Looking forward to your reply, thank you.

**Comment by hobincar** [comment]
Hi,

1. There’s run.py for you. You can check step 5. Inference in Readme.
2. It is not an error. That’s what I got, and I think I should search for better hyperparameters to train better.
