### ISSUE TITLE
IOError: [Errno 32] Broken pipe how to solve this error 

### ISSUE THREAD

**Issue by Savitha2018** [hobincar/RecNet#18]
[Epoch #1] loss: 4.759 = (CE: 4.759) + (Ent: 0.0 * 2959.694) + (Rec: 0.0 * 0.000): 100%|██████████| 244/244 [04:48<00:00,  1.18s/it]
train loss: 5.88176631732 (CE 5.88176631732 + E 2908.56674344 + REC 0.0)
{'reflen': 342, 'guess': [300, 200, 100, 0], 'testlen': 300, 'correct': [272, 140, 66, 0]}
ratio: 0.877192982454
Traceback (most recent call last):
  File "train.py", line 165, in <module>
    main()
  File "train.py", line 142, in main
    val_scores = evaluate(val_iter, model, model.vocab)
  File "/content/drive/My Drive/RecNet/utils.py", line 200, in evaluate
    scores = score(vid2pred, vid2GTs)
  File "/content/drive/My Drive/RecNet/utils.py", line 169, in score
    scores = calc_scores(refs, hypos)
  File "/content/drive/My Drive/RecNet/utils.py", line 188, in calc_scores
    score, scores = scorer.compute_score(ref, hypo)
  File "/content/drive/My Drive/RecNet/meteor/meteor.py", line 37, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "/content/drive/My Drive/RecNet/meteor/meteor.py", line 55, in _stat
    self.meteor_p.stdin.write('{}\n'.format(score_line))
IOError: [Errno 32] Broken pipe

how to solve this error

**Comment by hobincar** [comment]
Can you specify your environment settings? The python version, OS, java version, etc.

**Comment by Savitha2018** [comment]
i dont  have high end machine thats y i tried in google colab python 2 with gpu environment 

Python 2.7.15+
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

Thu Nov 28 11:24:04 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8    26W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by hobincar** [comment]
The different java version seems to be a problem, but I think it is related to [this issue](https://github.com/tylin/coco-caption/issues/17) as the error comes from [the evaluation codes in the repo](https://github.com/tylin/coco-caption).

**Comment by Savitha2018** [comment]
how to solve and implement this

**Comment by hobincar** [comment]
@Savitha2018 Can you try [this one](https://github.com/tylin/coco-caption/issues/17#issuecomment-333730601)?
