### ISSUE TITLE
How to extract 3D-ResNext Features?

### ISSUE THREAD

**Issue by Daic115** [hobincar/RecNet#19]
Hi hobincar,thanks for your excellent work！
I wonder how you extract the 3D-ResNext feature in your [video-feature-extractor](https://github.com/hobincar/pytorch-video-feature-extractor).
I have tried using pretrained 3d model weight from [here](https://github.com/kenshohara/3D-ResNets-PyTorch),and using feature-extractor under default setting, but at captioning stage ,the features which I extracted works far worse than your 3d-resnext features.
Could you please tell me some details about your features extractor setting?

**Comment by hobincar** [comment]
Hi,

Maybe [this repo](https://github.com/hobincar/video-classification-3d-cnn-pytorch) can help you. Based on [the original repo](https://github.com/kenshohara/video-classification-3d-cnn-pytorch), I uploaded a commit containing the changes for extracting 3D-ResNext features I used.

**Comment by Daic115** [comment]
Thank you very much!
