### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by nathanielhobbs** [hobincar/RecNet#27]
I've followed all the directions as closely as possible,  The only difference with the README is that I'm using CUDNN 7.0.3, but everything else is the same.  However, when I run train.py on stage one I get the following error:

(.recnetpy27) (base) [nh385@pascal002 RecNet]$ python train.py -c configs.train_stage1
MODEL ID: RecNet | MSVD | FEAT MSVD_InceptionV4 mcl-30 | EMB 468 | DEC uni-LSTM-l1-h512 at-256 | OPTIM AMSGrad lr-5e-05-dc-20-0.5-5-wd-1
e-05 reg-0.0 rec-0.0 | 200127-23:24:40
/scratch/nh385/RecNet/loader/data_loader.py:89: H5pyDeprecationWarning: dataset.value has been deprecated. Use dataset[()] instead.
  feats = fin[vid].value
#vocabs: 9687 (9683), #words: 346841 (346841). Trim words which appear less than 1 times.
/scratch/nh385/RecNet/.recnetpy27/lib/python2.7/site-packages/torch/nn/modules/rnn.py:54: UserWarning: dropout option adds dropout after
 all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))

[Epoch #1] loss: 4.649 = (CE: 4.649) + (Ent: 0.0 * 2122.213) + (Rec: 0.0 * 0.000): 100%|██████████| 244/244 [01:41<00:00,  2.41it/s]
train loss: 5.69164648408 (CE 5.69164648408 + E 2086.57494317 + REC 0.0)
Traceback (most recent call last):
  File "train.py", line 165, in <module>
    main()
  File "train.py", line 142, in main
    val_scores = evaluate(val_iter, model, model.vocab)
  File "/scratch/nh385/RecNet/utils.py", line 200, in evaluate
    scores = score(vid2pred, vid2GTs)
  File "/scratch/nh385/RecNet/utils.py", line 169, in score
    scores = calc_scores(refs, hypos)
  File "/scratch/nh385/RecNet/utils.py", line 182, in calc_scores
    (Meteor(),"METEOR"),
  File "/scratch/nh385/RecNet/pycocoevalcap/meteor/meteor.py", line 24, in __init__
    stderr=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

I'm not really sure which file/directory is missing, is there some standard way to handle this?

**Comment by hobincar** [comment]
[This issue](https://github.com/tylin/coco-caption/issues/22) looks similar to yours. Can you check it?

**Comment by hobincar** [comment]
If you're using Ubuntu or Debian, you can easily install java8 as follows.
```
$ sudo apt-get install openjdk-8-jdk
```
