### ISSUE TITLE
dimension mismatch of vocabulary

### ISSUE THREAD

**Issue by tuyunbin** [hobincar/RecNet#30]
https://github.com/hobincar/RecNet/blob/020b7fc4d71708ea256aa16ba87e153ee45543a5/configs/train_stage2.py#L16

Hi, I think you should add 'unk': 3 in train_stage2.py, or an error will be produced, that is,  size mismatch for out.weight: copying a param with shape torch.Size([9687, 512]) from checkpoint, the shape in current model is torch.Size([9686, 512]).

**Comment by hobincar** [comment]
Thanks! I should have changed like that, but I didn't accidentally. I'll fix it right away.
