### ISSUE TITLE
question about the Inception-v4 features

### ISSUE THREAD

**Issue by pandababyer** [hobincar/RecNet#31]
Hi, thanks for your great work and it is very helpful. My question is: the shape of the video in MSR-VTT_InceptionV4.hdf5 is n*1536 and i have no idea how to get the n. My understanding is that you choose the equally-spaced 28 features from the original whole frames so the number of n should all equal to 28 in all videos but it is not like that. the n varies and it confused me a lot. Looking forward to your reply and thx!

**Comment by hobincar** [comment]
Hi. The videos have different lengths so the number of frames/features *n* will vary. What you need to do is sample *n* frames/features from each video. This way, you can choose *n* as you want and have the same number of frames/features for all videos.

**Comment by pandababyer** [comment]
@hobincar thx!
