### ISSUE TITLE
About copying a param with shape torch.Size([13380,468]) from checkpoint,the shape in current model is torch.Size([13475,468])])

### ISSUE THREAD

**Issue by maoao686868** [hobincar/RecNet#32]
@hobincar 
Hello, when we download pretrained Recnet_Global model and  pretreated features from MSVD dataset to python run.py. I come across this problem:
Traceback (most recent call last):
  File "run.py", line 96, in <module>
    run('/root/Workspace/rn/checkpoint/RecNet-global_MSVD(1).ckpt')
  File "run.py", line 44, in run
    decoder.load_state_dict(checkpoint['decoder'])
  File "/root/anaconda3/envs/rn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Decoder:
	size mismatch for embedding.weight: copying a param with shape torch.Size([13380, 468]) from checkpoint, the shape in current model is torch.Size([13475, 468]).
	size mismatch for out.weight: copying a param with shape torch.Size([13380, 512]) from checkpoint, the shape in current model is torch.Size([13475, 512]).
	size mismatch for out.bias: copying a param with shape torch.Size([13380]) from checkpoint, the shape in current model is torch.Size([13475]).
Please help me, I feel very anxious about this problem.

**Comment by maoao686868** [comment]
@hobincar 
plus.I use environment as follows :  using anaconda3 create python3.6, pytorch 1.1,torchvision0.3.0

**Comment by hobincar** [comment]
Hi. The error message is saying that the model has 13475 vocabs but the checkpoint has 13380 vocabs. I guess the checkpoint is saved using the old implementation. I don't have much time for handling this for now, but I'll look at it. Maybe you can train the model by yourself instead of using my checkpoint file.

**Comment by maoao686868** [comment]
@hobincar  Sorry , this problem is because of my wrong virtual enviroment. I have sovled this problem, thanks for your reply.

**Comment by hobincar** [comment]
That's great :) Thank you for the information.
