### ISSUE TITLE
According to these codes, why do you need both train_stage1.py and train_stage2.py?

### ISSUE THREAD

**Issue by maoao686868** [hobincar/RecNet#33]
Hi, @hobincar. I am sorry to disturb you again. Since this 2018 paper "Reconstruction Network for Video Captioning " includes the reconstruction network, why do we still need train_stage1.py in this github project? We can directly train the network using train_stage2.py. I can't understand.

**Comment by hobincar** [comment]
Hi @maoao686868. I follow the two-stage training written in the paper (Section 3.3) where the encoder-decoder is trained on stage 1 and the encoder-decoder-reconstructor is trained on stage 2.

![image](https://user-images.githubusercontent.com/17702664/102734711-dba91480-4383-11eb-9fbc-726e5c11fb32.png)
