### ISSUE TITLE
RuntimeError: copy_if failed to synchronise: cudaErrorIllegalAddress: an illegal memory address was encountered

### ISSUE THREAD

**Issue by monic7** [hobincar/RecNet#34]
Hi @hobincar 

I encountered the following error when running the RecNet code:
![image](https://user-images.githubusercontent.com/72240037/102886676-83136d80-4490-11eb-81b2-5aca4f4fe852.png)

It appears to be coming from the Temporal Attention class, and same error message appears even when both energies and masks are on cpu and both on cuda.

May I know how to resolve this issue?
Thank you! :)

**Comment by hobincar** [comment]
Hi @monic7.
I'm sorry but I don't know what causes the error.
Can you check the environment (CUDA 9.0, cuDNN 7.3.1, Python 2.7, and PyTorch 1.0)?
