### ISSUE TITLE
Encoder recurrent neural network is missing.

### ISSUE THREAD

**Issue by nasib-ullah** [hobincar/RecNet#35]
Hello, first of all, I would like to thank you for your repositories regarding video captioning. It helped me a lot.
 While going through this repository I found out the encoder lstm/gru is missing. The extracted frame features are directly fed to the decoder model, while in the original paper it takes input from encoder lstm/gru.
Since the encoder lstm/gru is missing, the sequential relationship of the video has not been captured, maybe that is a reason for not getting the results that the original paper claimed.

**Comment by hobincar** [comment]
Hi @nasib104.
I think you're right. The RNN in the encoder is missing in this code. Adding it may close the performance gap between the original paper and the results of this repo. I'll look into it when I'm available. Thank you for the comment!
