### ISSUE TITLE
Where is config.py ?

### ISSUE THREAD

**Issue by xiaoyongbest1234** [hobincar/RecNet#5]
Where is `config.py` ?
I did not find the location of `config.py`, I only found `config_stage1.py` and `config_stage2.py`.

**Comment by hobincar** [comment]
Sorry, it is a typo. Originally, I used one configuration file named `config.py`. I tried to change the names of configuration files for consistency, but there can be still ones that I didn't check.

I'll change the typos in README now. If there's another, please let me know :)
