### ISSUE TITLE
I found an exception when I ran the 'python run.py' command.

### ISSUE THREAD

**Issue by xiaoyongbest1234** [hobincar/RecNet#7]
I had a problem when I ran the `python run.py` command.
```
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from config import EvalConfig as C
ImportError: No module named config
```
I look forward to your reply and thank you very much.

**Comment by Martin-top** [comment]
I think `from config import EvalConfig as C` should be updated to `from config_stage2 import EvalConfig as C`, or `from config_stage1 import EvalConfig as C`, right?

**Comment by hobincar** [comment]
You're right :) I recommend you to use `config_stage2`. I'll fix it right away.
