### ISSUE TITLE
When I run the 'python train.py-c configs.train_stage1' command, I find an error.

### ISSUE THREAD

**Issue by Martin-top** [hobincar/RecNet#9]
When I run `python train.py-c configs.train_stage1`, I find an error.
I only extracted the features of the `MSVD `dataset, and did not extract the `MSR-VTT` dataset. When I run `python train.py-c configs.train_stage1`, the following error occurred.
Can you provide `total. json`, `train.json`, `val.json`, `test.json`?

```
MODEL ID: RecNet | MSR-VTT | FEAT MSR-VTT_InceptionV4 mcl-30 | EMB 468 | DEC uni-LSTM-l1-h512 at-256 | REC uni-LSTM-l1-h1536 | OPTIM AMSGrad lr-0.0002-dc-20-0.5-5-wd-1e-05 reg-0.0 rec-0.0 | 191009-08:31:39
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    main()
  File "train.py", line 118, in main
    train_iter, val_iter, test_iter, vocab = build_loaders(C)
  File "train.py", line 29, in build_loaders
    corpus = MSRVTT(C)
  File "/home/test/LXY2/RecNet/loader/MSRVTT.py", line 36, in __init__
    super(MSRVTT, self).__init__(C, MSRVTTVocab, MSRVTTDataset)
  File "/home/test/LXY2/RecNet/loader/data_loader.py", line 143, in __init__
    self.build()
  File "/home/test/LXY2/RecNet/loader/data_loader.py", line 146, in build
    self.build_vocab()
  File "/home/test/LXY2/RecNet/loader/data_loader.py", line 154, in build_vocab
    transform=self.transform_sentence)
  File "/home/test/LXY2/RecNet/loader/data_loader.py", line 29, in __init__
    self.build()
  File "/home/test/LXY2/RecNet/loader/data_loader.py", line 35, in build
    captions = self.load_captions()
  File "/home/test/LXY2/RecNet/loader/MSRVTT.py", line 10, in load_captions
    with open(self.caption_fpath, 'r') as fin:
IOError: [Errno 2] No such file or directory: 'data/MSR-VTT/metadata/total.json'
```

**Comment by Martin-top** [comment]
I have one more question:
Run `python train.py-c configs.train_stage1` command only with `MSVD `dataset, why will it prompt the error of `MSR-VTT`? Do both datasets need to exist at the same time?

**Comment by hobincar** [comment]
It seems that I accidentally commit the setting when we train with the MSR-VTT dataset. I'll change it back to the MSVD setting.

FYI, you can change which dataset to use in [here](https://github.com/hobincar/RecNet/blob/master/configs/train_stage1.py#L124), and the corresponding feature to use in [here](https://github.com/hobincar/RecNet/blob/master/configs/train_stage1.py#L38)

* Q&A (1)
  > Can you provide total. json, train.json, val.json, test.json?

  You can automatically get it when you split MSR-VTT dataset.

* Q&A (2)
  > I have one more question:
Run `python train.py-c configs.train_stage1` command only with `MSVD `dataset, why will it prompt the error of `MSR-VTT`? Do both datasets need to exist at the same time?

  We don't need both datasets when we train with one of them.

**Comment by Martin-top** [comment]
Hi, thank you very much for your patience. I have successfully solved the above problem.But at the same time I have the following questions for you.Looking forward to your reply. Thank you very much.

1. How can I train `RecNet(local)` after I finish training `RecNet(global)`?
My idea is to set `reconstructor_type = 'local' `of `TrainConfig` of `configs/train_stage2.py`, right? Do I need to modify anything else besides that?
2. In preparation for training RecNet (global) before, why did you set `pretrained_decoder_fpath = "checkpoints/RecNet - global | MSVD ... ... "`,not `pretrained_decoder_fpath = "checkpoints/RecNet | MSVD ... ... "`.
3. Why do you set `ckpt_fpath = "checkpoints/SA - LSTM | MSVD | ..." `of `EvalConfig` of `configs/train_stage2.py`? I don't know why is set to `"checkpoints/SA - LSTM"`,this is a mistake?
When is this `EvalConfig`used?

**Comment by hobincar** [comment]
Hi,

1. Yes. That's the only thing that you have to change.

2. I'm not quite sure, but I think that's because the old code used to share the same configuration file for training and evaluation, and the `pretrained_decoder_fpath` was set to evaluate the `RecNet-global` model after training. However, since I separated the configuration file for training and evaluation, it will be awkward to use `checkpoints/RecNet - global | MSVD ... ...` as you said.

3. If you see the paper, the RecNet is based on the SA-LSTM (RecNet = SA-LSTM + reconstructor). So originally, I loaded the pretrained model from [this repo](https://github.com/hobincar/SA-LSTM). That's why we have `SA-LSTM` in the path. And the `EvalConfig` is, actually I tried to separate the configuration for evaluation (or running a model) into `configs/run.py`, but I forgot to remove the `EvalConfig` from `configs/train_stage2.py`. I'll fix it!
